name: Build-dist

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Build For Windows
      if: matrix.os == 'windows-latest'
      run: |
        python -m pip install --upgrade pip
        if (Test-Path requirements.txt -PathType leaf) {
          pip install -r requirements.txt
        }
        python -c "import numpy; print(numpy.__version__)"
        python -c "import colour; print(colour.__version__)"
        pyinstaller -F ssa_hdrify.py


    - name: Upload Build Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ssa-hdrify-${{ matrix.os }}
        path: dist
