name: Build-dist

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: version
        run: echo "version=$(<VERSION)" >> $GITHUB_OUTPUT

  build:
    runs-on: ${{ matrix.os }}-latest
    needs: get-version
    strategy:
      matrix:
        os: [ macos, windows, ubuntu ]

    steps:
      - uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Windows dependency
        if: matrix.os == 'windows'
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt -PathType leaf) {
            pip install -r requirements.txt
          }

      - name: Mac/Linux dependency
        if: matrix.os == 'macos' || matrix.os == 'ubuntu'
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
              pip install -r requirements.txt
          fi

      - name: Windows Build
        if: matrix.os == 'windows'
        run: |
          pyinstaller -y ssa_hdrify.spec

      - name: Mac/Linux Build
        if: matrix.os == 'macos' || matrix.os == 'ubuntu'
        run: |
          pyinstaller -y ssa_hdrify.spec -- --app-version=$(<VERSION)

      - name: Mac clean up dist folder
        if: matrix.os == 'macos'
        run: rm -rf dist/ssa_hdrify

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ssa-hdrify-${{ matrix.os }}-${{ needs.get-version.outputs.version }}
          path: dist
